// London-BOS PWA — Control Room Editorial: datos reales por Tailscale, solo lectura y decisiones legibles en móvil.
import { useEffect, useMemo, useRef, useState, type ReactNode, type TouchEvent } from "react";
import {
  Activity, ArrowUpRight, Bell, BookOpen, CalendarDays, CheckCircle2,
  ChevronRight, Clock3, Database, GitBranch, LayoutDashboard, LineChart,
  ListTree, LockKeyhole, Menu, Radio, RefreshCw, Settings2, ShieldCheck,
  Sparkles, Target, TimerReset, TrendingUp, X, Zap,
} from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

const CONTROL_ROOM = "/manus-storage/london-bos-control-room_3a48b6ed.jpg";
const LEDGER_TEXTURE = "/manus-storage/london-bos-ledger-texture_db4ff039.jpg";
const API_URL = import.meta.env.VITE_LONDON_BOS_API_URL || "";

type View = "overview" | "strategy" | "config" | "sessions" | "paper" | "events" | "roadmap" | "live";
type ConnectionState = "demo" | "live" | "offline" | "stale";
type Period = "today" | "week" | "month" | "all";
type ModuleKey = "sessions" | "events" | "paper";
type ModuleState = "loading" | "ready" | "empty" | "error";
type ModuleStates = Record<ModuleKey, ModuleState>;
type Session = { fecha: string; generado?: string; maximo: number; minimo: number; rango_pips: number; operable: boolean };
type EventItem = { id: number; event: string; timestamp: string; source: string; session_date: string; direction?: string | null; price?: number | null; r_multiple?: number | null; metadata?: Record<string, unknown> | null; metadata_legacy?: string | null };
type PaperTrade = { fecha?: string; date?: string; direccion?: string; direction?: string; salida?: string; exit?: string; r?: number | null; r_multiple?: number | null; entry?: number | null; sl?: number | null; tp?: number | null };
type Health = { data_status?: "fresh" | "stale" | "unknown"; api_status?: string; dependency_status?: string; last_session_date?: string; last_sesion_date?: string; data_age_hours?: number; freshness_threshold_hours?: number; dependencies?: Record<string, string> };
type PaperSummary = { realizedR: number; closed: number; won: number; lost: number; flat: number; unresolved: number; skipped: number };

const VIEW_ORDER: View[] = ["overview", "strategy", "config", "sessions", "paper", "events", "roadmap", "live"];
const PERIODS: { id: Period; label: string }[] = [{ id: "today", label: "Hoy" }, { id: "week", label: "Semana" }, { id: "month", label: "Mes" }, { id: "all", label: "Todo" }];

const demoSessions: Session[] = [
  { fecha: "2026-08-19", maximo: 1.15968, minimo: 1.15737, rango_pips: 23.1, operable: true },
  { fecha: "2026-08-16", maximo: 1.15942, minimo: 1.15738, rango_pips: 20.5, operable: true },
  { fecha: "2026-08-13", maximo: 1.15441, minimo: 1.15322, rango_pips: 12, operable: false },
];
const demoEvents: EventItem[] = [
  { id: 10, event: "PAPER_TRADE_COMPLETED", timestamp: "2026-08-19T11:00:00-05:00", source: "EURUSD", session_date: "2026-08-19", direction: "BUY", r_multiple: 1.5 },
  { id: 9, event: "JOB_COMPLETED", timestamp: "2026-08-19T11:00:00-05:00", source: "LONDON-BOS", session_date: "2026-08-19" },
];
const demoPaper: PaperTrade[] = [
  { fecha: "2026-08-19", direccion: "BUY", salida: "TP", r: 1.5, entry: 1.15968, sl: 1.15768, tp: 1.16268 },
  { fecha: "2026-08-16", direccion: "BUY", salida: "ABIERTA_11H", r: 0.3, entry: 1.15942, sl: 1.15742, tp: 1.16242 },
];
const roadmap = [
  { phase: "01", title: "Seguridad y saneamiento", detail: "Secretos, DB y logs fuera de Git", status: "done" },
  { phase: "02", title: "Dominio común", detail: "Contratos y reglas puras compartidas", status: "done" },
  { phase: "03", title: "API read-only", detail: "Health, sesiones, paper trades y eventos", status: "done" },
  { phase: "04", title: "Observabilidad endurecida", detail: "Freshness, idempotencia y metadata JSON", status: "done" },
  { phase: "05", title: "PWA operativa", detail: "Decisión móvil, métricas y estados vivos", status: "active" },
  { phase: "06", title: "Canal privado", detail: "Tailscale Serve activo y validado", status: "done" },
];

function asRecord(value: unknown): Record<string, unknown> { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function stringValue(value: unknown): string | undefined { return typeof value === "string" ? value : value == null ? undefined : String(value); }
function numberValue(value: unknown): number | null { const parsed = typeof value === "number" ? value : typeof value === "string" ? Number(value) : NaN; return Number.isFinite(parsed) ? parsed : null; }
function booleanValue(value: unknown): boolean { return value === true || value === 1 || value === "1" || value === "true"; }
function unpackList<T>(payload: unknown, collectionKeys: string[]): T[] { if (Array.isArray(payload)) return payload as T[]; const record = asRecord(payload); for (const key of ["data", "items", "results", ...collectionKeys]) { const candidate = record[key]; if (Array.isArray(candidate)) return candidate as T[]; } return []; }
function normalizeSession(value: unknown): Session { const row = asRecord(value); return { fecha: stringValue(row.fecha ?? row.date) || "", generado: stringValue(row.generado ?? row.generated_at), maximo: numberValue(row.maximo ?? row.high) ?? 0, minimo: numberValue(row.minimo ?? row.low) ?? 0, rango_pips: numberValue(row.rango_pips ?? row.range_pips) ?? 0, operable: booleanValue(row.operable ?? row.is_operable) }; }
function normalizePaperTrade(value: unknown): PaperTrade { const row = asRecord(value); return { fecha: stringValue(row.fecha ?? row.date), direccion: stringValue(row.direccion ?? row.direction), salida: stringValue(row.salida ?? row.exit), r: numberValue(row.r ?? row.r_multiple), entry: numberValue(row.entry), sl: numberValue(row.sl), tp: numberValue(row.tp) }; }
function normalizeEvent(value: unknown): EventItem { const row = asRecord(value); const metadata = asRecord(row.metadata_json); const rawEvent = stringValue(row.event ?? row.event_type) || "EVENT"; const exit = stringValue(metadata.salida ?? row.salida) || ""; const event = rawEvent === "PAPER_TRADE_COMPLETED" && exit.includes("ABIERTA_11H") ? "PAPER_CYCLE_CUTOFF" : rawEvent; return { id: numberValue(row.id) ?? 0, event, timestamp: stringValue(row.timestamp ?? row.created_at) || "", source: stringValue(row.source ?? row.symbol) || "London-BOS", session_date: stringValue(row.session_date ?? metadata.session_date ?? metadata.fecha) || "—", direction: stringValue(row.direction ?? metadata.direction ?? metadata.direccion) ?? null, price: numberValue(row.price ?? metadata.price), r_multiple: numberValue(row.r_multiple ?? row.r ?? metadata.r_multiple ?? metadata.r), metadata: Object.keys(metadata).length ? metadata : null, metadata_legacy: stringValue(row.metadata_legacy ?? row.metadata) ?? null }; }

function parseCalendarDate(value?: string): Date | null {
  if (!value) return null;
  const match = /^(\d{4})-(\d{2})-(\d{2})$/.exec(value);
  if (match) return new Date(Number(match[1]), Number(match[2]) - 1, Number(match[3]), 12);
  const parsed = new Date(value);
  return Number.isNaN(parsed.getTime()) ? null : parsed;
}
function dayKey(value?: string): string { const date = parseCalendarDate(value); return date ? `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}` : ""; }
function formatDate(value?: string) { const date = parseCalendarDate(value); return date ? new Intl.DateTimeFormat("es-ES", { day: "2-digit", month: "short" }).format(date) : "—"; }
function formatTime(value?: string) { return value ? new Intl.DateTimeFormat("es-ES", { hour: "2-digit", minute: "2-digit" }).format(new Date(value)) : "—"; }
function formatPrice(value?: number | null) { return value == null ? "—" : value.toFixed(5); }
function formatR(value: number) { return `${value >= 0 ? "+" : ""}${value.toFixed(2)}R`; }
function tradeExit(trade: PaperTrade) { return (trade.salida ?? trade.exit ?? "—").toUpperCase(); }
function tradeDirection(trade: PaperTrade) { return (trade.direccion ?? trade.direction ?? "—").toUpperCase(); }
function isSkipped(trade: PaperTrade) { return tradeExit(trade) === "SKIP" || tradeDirection(trade) === "NO_OPERABLE"; }
function isAtCutoff(trade: PaperTrade) { return tradeExit(trade).includes("ABIERTA") || tradeExit(trade).includes("OPEN"); }
function isRealized(trade: PaperTrade) { return !isSkipped(trade) && !isAtCutoff(trade) && Number.isFinite(Number(trade.r ?? trade.r_multiple)); }
function tradeStatusLabel(trade: PaperTrade) { return isAtCutoff(trade) ? "AL CORTE 11:00" : tradeExit(trade); }
function tradeDate(trade: PaperTrade) { return parseCalendarDate(trade.fecha ?? trade.date); }
function sessionCycleLabel(session?: Session) { if (!session) return "—"; const generated = parseCalendarDate(session.generado); const date = parseCalendarDate(session.fecha); if (date && generated && dayKey(session.fecha) !== dayKey(session.generado)) return `Asia ${formatDate(session.fecha)}→${formatDate(session.generado)}`; return `Asia ${formatDate(session.fecha)}`; }
function inPeriod(trade: PaperTrade, period: Period): boolean {
  if (period === "all") return true;
  const date = tradeDate(trade); if (!date) return false;
  const today = new Date(); today.setHours(12, 0, 0, 0);
  if (period === "today") return date.getTime() === today.getTime();
  if (period === "month") return date.getFullYear() === today.getFullYear() && date.getMonth() === today.getMonth();
  const monday = new Date(today); monday.setDate(today.getDate() - ((today.getDay() + 6) % 7));
  const sunday = new Date(monday); sunday.setDate(monday.getDate() + 7);
  return date >= monday && date < sunday;
}
function paperSummary(trades: PaperTrade[]): PaperSummary {
  return trades.reduce<PaperSummary>((summary, trade) => {
    if (isSkipped(trade)) { summary.skipped += 1; return summary; }
    if (isAtCutoff(trade)) { summary.unresolved += 1; return summary; }
    if (!isRealized(trade)) return summary;
    const r = Number(trade.r ?? trade.r_multiple ?? 0);
    summary.realizedR += r; summary.closed += 1;
    if (r > 0) summary.won += 1; else if (r < 0) summary.lost += 1; else summary.flat += 1;
    return summary;
  }, { realizedR: 0, closed: 0, won: 0, lost: 0, flat: 0, unresolved: 0, skipped: 0 });
}
function buildEquityData(trades: PaperTrade[]) {
  let equity = 0;
  return [...trades].filter(isRealized).sort((a, b) => (tradeDate(a)?.getTime() || 0) - (tradeDate(b)?.getTime() || 0)).map((trade) => { equity += Number(trade.r ?? trade.r_multiple ?? 0); return { day: formatDate(trade.fecha ?? trade.date), r: Number(equity.toFixed(2)) }; });
}
function buildRangeData(sessions: Session[]) {
  const buckets = [{ bucket: "<15", min: -Infinity, max: 15 }, { bucket: "15–20", min: 15, max: 20 }, { bucket: "20–30", min: 20, max: 30 }, { bucket: "30–40", min: 30, max: 40 }, { bucket: ">40", min: 40, max: Infinity }];
  return buckets.map((bucket) => { const included = sessions.filter((session) => session.rango_pips >= bucket.min && session.rango_pips < bucket.max); return { bucket: bucket.bucket, sessions: included.length, operable: included.filter((session) => session.operable).length }; });
}
async function fetchJson<T>(path: string): Promise<T> { const response = await fetch(`${API_URL}${path}`, { headers: { Accept: "application/json" } }); if (!response.ok) throw new Error(`HTTP ${response.status}`); return response.json() as Promise<T>; }

function StatusPill({ state }: { state: ConnectionState }) { const copy = state === "live" ? "API LIVE" : state === "stale" ? "API STALE" : state === "offline" ? "API OFFLINE" : "MODO DEMO"; return <span className={`status-pill ${state}`}><span className="status-dot" />{copy}</span>; }
function AccessNotice({ state }: { state: ConnectionState }) { const connected = state === "live" || state === "stale"; return <div className={`access-notice ${connected ? "connected" : "private"}`} role="status"><div className="access-notice-icon">{connected ? <ShieldCheck size={16} /> : <LockKeyhole size={16} />}</div><div><strong>{connected ? "Datos reales bajo canal privado" : "Interfaz pública · datos reales protegidos"}</strong><span>{connected ? "Este dispositivo consulta London-BOS mediante Tailscale. La API permanece read-only." : "La interfaz se abre desde Vercel, pero los datos reales requieren un dispositivo autorizado dentro de Tailscale."}</span></div><StatusPill state={state} /></div>; }

export default function Home() {
  const [view, setView] = useState<View>("overview");
  const [mobileOpen, setMobileOpen] = useState(false);
  const [isMobileApp, setIsMobileApp] = useState(false);
  const [viewDirection, setViewDirection] = useState<"forward" | "back">("forward");
  const touchStart = useRef<{ x: number; y: number } | null>(null);
  const [sessions, setSessions] = useState(demoSessions);
  const [events, setEvents] = useState(demoEvents);
  const [paperTrades, setPaperTrades] = useState(demoPaper);
  const [connection, setConnection] = useState<ConnectionState>("demo");
  const [health, setHealth] = useState<Health>({});
  const [lastSync, setLastSync] = useState("demo local · sin endpoint configurado");
  const [moduleStates, setModuleStates] = useState<ModuleStates>({ sessions: "ready", events: "ready", paper: "ready" });
  const [moduleErrors, setModuleErrors] = useState<Record<ModuleKey, string | null>>({ sessions: null, events: null, paper: null });

  const refresh = async () => {
    if (!API_URL) { setConnection("demo"); return; }
    try {
      const [sessionsResult, eventsResult, paperResult, healthResult] = await Promise.allSettled([
        fetchJson<unknown>("/api/session/history?limit=30"), fetchJson<unknown>("/api/events?limit=50"), fetchJson<unknown>("/api/paper-trades?limit=30"), fetchJson<Health>("/api/health"),
      ]);
      if (healthResult.status !== "fulfilled") throw healthResult.reason;
      const applyCollection = <T,>(key: ModuleKey, result: PromiseSettledResult<unknown>, keys: string[], normalizer: (value: unknown) => T, commit: (items: T[]) => void) => {
        if (result.status === "fulfilled") { const items = unpackList<unknown>(result.value, keys).map(normalizer); commit(items); setModuleStates((current) => ({ ...current, [key]: items.length ? "ready" : "empty" })); setModuleErrors((current) => ({ ...current, [key]: null })); }
        else { commit([]); setModuleStates((current) => ({ ...current, [key]: "error" })); setModuleErrors((current) => ({ ...current, [key]: "No se pudo leer este endpoint." })); }
      };
      applyCollection("sessions", sessionsResult, ["sessions", "history"], normalizeSession, setSessions);
      applyCollection("events", eventsResult, ["events"], normalizeEvent, setEvents);
      applyCollection("paper", paperResult, ["paper_trades", "paperTrades", "trades"], normalizePaperTrade, setPaperTrades);
      setHealth(healthResult.value); setConnection(healthResult.value.data_status === "stale" ? "stale" : "live");
      setLastSync(new Intl.DateTimeFormat("es-ES", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" }).format(new Date()));
    } catch {
      setConnection("offline"); setLastSync("último intento fallido");
      setModuleStates({ sessions: "error", events: "error", paper: "error" });
      setModuleErrors({ sessions: "No se pudo contactar la API.", events: "No se pudo contactar la API.", paper: "No se pudo contactar la API." });
    }
  };

  useEffect(() => { const query = window.matchMedia("(max-width: 760px)"); const detect = () => setIsMobileApp(query.matches || (navigator.maxTouchPoints > 0 && window.matchMedia("(pointer: coarse)").matches)); detect(); query.addEventListener?.("change", detect); return () => query.removeEventListener?.("change", detect); }, []);
  useEffect(() => { refresh(); const timer = window.setInterval(refresh, 30000); return () => window.clearInterval(timer); }, []);

  const operableCount = sessions.filter((item) => item.operable).length;
  const avgRange = sessions.length ? sessions.reduce((sum, item) => sum + item.rango_pips, 0) / sessions.length : 0;
  const navItems = [{ id: "overview" as View, label: "Resumen", icon: LayoutDashboard }, { id: "strategy" as View, label: "Estrategia", icon: BookOpen }, { id: "config" as View, label: "Configuración", icon: Settings2 }, { id: "sessions" as View, label: "Sesiones", icon: CalendarDays }, { id: "paper" as View, label: "Paper trading", icon: TrendingUp }, { id: "events" as View, label: "Eventos", icon: ListTree }, { id: "roadmap" as View, label: "Roadmap", icon: GitBranch }, { id: "live" as View, label: "Trading real", icon: LockKeyhole }];
  const title = navItems.find((item) => item.id === view)?.label || "Resumen";
  const moveTo = (next: View) => { if (next === view) return; setViewDirection(VIEW_ORDER.indexOf(next) >= VIEW_ORDER.indexOf(view) ? "forward" : "back"); setView(next); setMobileOpen(false); };
  const handleTouchStart = (event: TouchEvent<HTMLElement>) => { const target = event.target as HTMLElement; if (target.closest("button, a, input, textarea, select")) return; const touch = event.touches[0]; touchStart.current = touch ? { x: touch.clientX, y: touch.clientY } : null; };
  const handleTouchEnd = (event: TouchEvent<HTMLElement>) => { if (!isMobileApp || !touchStart.current) return; const touch = event.changedTouches[0]; const dx = touch.clientX - touchStart.current.x; const dy = touch.clientY - touchStart.current.y; touchStart.current = null; if (Math.abs(dx) < 72 || Math.abs(dx) < Math.abs(dy) * 1.35) return; const current = VIEW_ORDER.indexOf(view); const nextIndex = dx < 0 ? Math.min(VIEW_ORDER.length - 1, current + 1) : Math.max(0, current - 1); if (nextIndex !== current) moveTo(VIEW_ORDER[nextIndex]); };

  return <div className={`dashboard-shell ${isMobileApp ? "mobile-app-mode" : "desktop-console-mode"}`}>
    <aside className={`app-sidebar ${mobileOpen ? "open" : ""}`}><div className="brand-lockup"><div className="brand-mark" aria-label="Monograma LB"><div className="brand-mark-diagonal" /></div><div><div className="brand-name">LONDON<span>·</span>BOS</div><div className="brand-kicker">OPERATIONS CONSOLE</div></div><button className="mobile-close" onClick={() => setMobileOpen(false)} aria-label="Cerrar menú"><X size={18} /></button></div><div className="sidebar-rule" /><div className="nav-label">Espacio de trabajo</div><nav className="main-nav" aria-label="Navegación principal">{navItems.map(({ id, label, icon: Icon }) => <button key={id} className={view === id ? "active" : ""} onClick={() => moveTo(id)}><Icon size={17} /><span>{label}</span>{view === id && <ChevronRight size={14} className="nav-arrow" />}</button>)}</nav><div className="sidebar-spacer" /><div className="sidebar-status"><div className="sidebar-status-head"><span>System status</span><ShieldCheck size={15} /></div><StatusPill state={connection} /><div className="sidebar-status-copy">Read-only by design. La ejecución real permanece bloqueada.</div></div><div className="sidebar-footer"><span>v0.4.0 PWA</span><span>CONTROL ROOM</span></div></aside>
    {mobileOpen && <button className="mobile-overlay" onClick={() => setMobileOpen(false)} aria-label="Cerrar menú" />}
    <main className="main-canvas"><AccessNotice state={connection} /><div className="mobile-app-strip"><div className="mobile-app-brand"><div className="brand-mark" aria-hidden="true"><div className="brand-mark-diagonal" /></div><div><strong>LONDON·BOS</strong><span>Conversación operativa</span></div></div><div className="mobile-app-actions"><StatusPill state={connection} /><button className="mobile-app-menu" onClick={() => setMobileOpen(true)} aria-label="Abrir módulos"><Menu size={19} /></button></div></div><header className="topbar"><div className="topbar-left"><button className="mobile-menu" onClick={() => setMobileOpen(true)} aria-label="Abrir menú"><Menu size={20} /></button><span className="eyebrow">LONDON-BOS / {title.toUpperCase()}</span></div><div className="topbar-actions"><span className="sync-label"><span className="sync-pulse" /> {lastSync}</span><Button variant="outline" size="sm" onClick={refresh} className="refresh-button"><RefreshCw size={14} /> Actualizar</Button><button className="icon-button" aria-label="Notificaciones"><Bell size={17} /><span /></button></div></header>
      <section key={view} className={`content-wrap view-stage ${viewDirection}`} onTouchStart={handleTouchStart} onTouchEnd={handleTouchEnd}>{view === "overview" && <Overview sessions={sessions} trades={paperTrades} events={events} avgRange={avgRange} operableCount={operableCount} connection={connection} health={health} onView={moveTo} />}{view === "strategy" && <StrategyView onBack={() => moveTo("overview")} />}{view === "config" && <ConfigView health={health} onBack={() => moveTo("overview")} />}{view === "sessions" && <SessionsView sessions={sessions} state={moduleStates.sessions} error={moduleErrors.sessions} onBack={() => moveTo("overview")} />}{view === "paper" && <PaperView trades={paperTrades} state={moduleStates.paper} error={moduleErrors.paper} onBack={() => moveTo("overview")} />}{view === "events" && <EventsView events={events} state={moduleStates.events} error={moduleErrors.events} onBack={() => moveTo("overview")} />}{view === "roadmap" && <RoadmapView onBack={() => moveTo("overview")} />}{view === "live" && <LiveView onBack={() => moveTo("overview")} />}</section>
    </main><nav className="mobile-bottom-nav" aria-label="Navegación móvil"><button className={view === "overview" ? "active" : ""} onClick={() => moveTo("overview")}><LayoutDashboard size={18} /><span>Resumen</span></button><button className={view === "sessions" ? "active" : ""} onClick={() => moveTo("sessions")}><CalendarDays size={18} /><span>Sesiones</span></button><button className={view === "paper" ? "active" : ""} onClick={() => moveTo("paper")}><TrendingUp size={18} /><span>Paper</span></button><button className={view === "events" ? "active" : ""} onClick={() => moveTo("events")}><ListTree size={18} /><span>Eventos</span></button></nav></div>;
}

function Overview({ sessions, trades, events, avgRange, operableCount, connection, health, onView }: { sessions: Session[]; trades: PaperTrade[]; events: EventItem[]; avgRange: number; operableCount: number; connection: ConnectionState; health: Health; onView: (v: View) => void }) {
  const latest = sessions[0]; const latestTrade = trades[0];
  const todayStats = paperSummary(trades.filter((trade) => inPeriod(trade, "today")));
  const weekStats = paperSummary(trades.filter((trade) => inPeriod(trade, "week")));
  const allStats = paperSummary(trades);
  const performanceData = buildEquityData(trades);
  const rangeData = buildRangeData(sessions);
  const strategyState = latest?.operable ? "OPERABLE" : "NO OPERABLE";
  const strategyCopy = latest ? latest.operable ? `Box asiático de ${latest.rango_pips.toFixed(1)} pips dentro de la ventana 15–40.` : `Box asiático de ${latest.rango_pips.toFixed(1)} pips fuera de la ventana 15–40.` : "Esperando una sesión registrada.";
  return <>
    <section className="strategy-brief"><div className="strategy-brief-top"><div><span className="panel-eyebrow">Estado de estrategia</span><strong className={latest?.operable ? "positive" : "negative"}>{strategyState}</strong><p>{strategyCopy}</p></div><div className={`strategy-stamp ${latest?.operable ? "operable" : "blocked"}`}><span>{latest?.rango_pips?.toFixed(1) || "—"}</span><small>PIPS</small></div></div><div className="strategy-quick"><QuickMetric label="Sesión Asia" value={sessionCycleLabel(latest)} detail={latest?.operable ? "señal habilitada" : "sin señal"} /><QuickMetric label="R realizado hoy" value={formatR(todayStats.realizedR)} detail={`${todayStats.closed} cierres confirmados`} tone={todayStats.realizedR < 0 ? "negative" : "positive"} /><QuickMetric label="Último paper" value={latestTrade ? tradeStatusLabel(latestTrade) : "—"} detail={latestTrade ? formatDate(latestTrade.fecha ?? latestTrade.date) : "sin registros"} /></div></section>
    <section className="mobile-inbox" aria-label="Bandejas operativas"><div className="mobile-inbox-heading"><div><span className="panel-eyebrow">Quick resume</span><h2>London-BOS</h2></div><span className="mobile-unread">{events.length || 0} eventos</span></div><button className="mobile-thread" onClick={() => onView("sessions")}><span className="thread-avatar thread-red"><CalendarDays size={18} /></span><span className="thread-copy"><strong>Sesión Londres</strong><small>{latest?.operable ? "Dentro de rango · señal operable" : "Fuera de rango · sin señal"}</small></span><span className="thread-meta"><b>{latest ? sessionCycleLabel(latest) : "—"}</b><ChevronRight size={16} /></span></button><button className="mobile-thread" onClick={() => onView("paper")}><span className="thread-avatar thread-blue"><TrendingUp size={18} /></span><span className="thread-copy"><strong>Paper trading</strong><small>{todayStats.unresolved ? `${todayStats.unresolved} al corte 11:00 · R no realizado` : "R realizado del día"}</small></span><span className="thread-meta"><b>{formatR(todayStats.realizedR)}</b><ChevronRight size={16} /></span></button><button className="mobile-thread" onClick={() => onView("events")}><span className="thread-avatar thread-ink"><ListTree size={18} /></span><span className="thread-copy"><strong>Eventos del sistema</strong><small>{connection === "demo" ? "Vista local · sin endpoint" : "Último ciclo auditado"}</small></span><span className="thread-meta"><b>{events.length}</b><ChevronRight size={16} /></span></button></section>
    <section className="hero-panel" style={{ backgroundImage: `linear-gradient(90deg, rgba(244,241,232,.98) 0%, rgba(244,241,232,.87) 42%, rgba(244,241,232,.36) 100%), url(${CONTROL_ROOM})` }}><div className="hero-copy"><div className="section-kicker"><span className="kicker-line" /> INFORME OPERATIVO DIARIO</div><h1>La sesión<br /><em>{latest?.operable ? "está dentro de rango." : "está fuera de rango."}</em></h1><p>Lectura rápida de estrategia, resultados paper y trazabilidad, sin tocar la ejecución.</p><div className="hero-meta"><span><Clock3 size={14} /> {sessionCycleLabel(latest)}</span><span><Radio size={14} /> EUR/USD · London Breakout</span></div></div><div className="hero-evidence"><span>LB / LIVE BOARD</span><span>SOURCE · IB + SQLITE</span><span>MODE · READ ONLY</span></div><div className="hero-signal"><div className="signal-ring"><div className="signal-core"><span>{latest?.rango_pips?.toFixed(1) || "—"}</span><small>PIPS</small></div></div><div className="signal-caption"><span className="signal-mark">{latest?.operable ? "✓" : "!"}</span><div><strong>{strategyState}</strong><small>Ventana válida 15–40 pips</small></div></div></div></section>
    <section className="metric-strip"><Metric icon={Activity} label="Estado datos" value={connection === "live" ? "FRESH" : connection === "stale" ? "STALE" : connection === "offline" ? "OFFLINE" : "DEMO"} note={health.data_age_hours ? `${health.data_age_hours.toFixed(1)}h de antigüedad` : "sin endpoint"} tone={connection === "stale" || connection === "offline" ? (connection === "offline" ? "red" : "amber") : "lime"} /><Metric icon={Target} label="Rango medio" value={`${avgRange.toFixed(1)} pips`} note="últimas sesiones" /><Metric icon={Zap} label="Operable" value={`${operableCount}/${sessions.length}`} note="sesiones en zona" tone="lime" /><Metric icon={LineChart} label="R realizado" value={formatR(allStats.realizedR)} note={`${allStats.closed} cierres confirmados`} tone={allStats.realizedR < 0 ? "red" : "blue"} /></section>
    <div className="overview-grid"><section className="panel performance-panel"><PanelHeading eyebrow="Paper trading / equity" title="R realizado acumulado" action="Abrir paper" onClick={() => onView("paper")} /><div className="chart-legend"><span><i className="legend-line" /> Equity acumulada en R</span><span className="muted-legend">Semana · {formatR(weekStats.realizedR)}</span></div><div className="chart-box">{performanceData.length ? <ResponsiveContainer width="100%" height="100%"><AreaChart data={performanceData} margin={{ top: 8, right: 8, bottom: 0, left: -22 }}><defs><linearGradient id="equityFillPwa" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#C51F2A" stopOpacity={0.32} /><stop offset="100%" stopColor="#C51F2A" stopOpacity={0.02} /></linearGradient></defs><CartesianGrid stroke="#dcd8cd" strokeDasharray="2 5" vertical={false} /><XAxis dataKey="day" tickLine={false} axisLine={false} tick={{ fontSize: 10, fill: "#7d8275" }} /><YAxis tickLine={false} axisLine={false} tick={{ fontSize: 10, fill: "#7d8275" }} /><Tooltip contentStyle={{ border: "1px solid #dcd8cd", borderRadius: 8, background: "#fffdf8", fontSize: 12 }} /><Area type="monotone" dataKey="r" stroke="#123B66" strokeWidth={2.5} fill="url(#equityFillPwa)" /></AreaChart></ResponsiveContainer> : <CollectionNotice state="empty" error={null} label="cierres realizados" />}</div></section><section className="panel range-panel"><PanelHeading eyebrow="Session filter" title="Dónde está la señal" action="Abrir sesiones" onClick={() => onView("sessions")} /><div className="chart-annotation"><span>{sessions.length} sesiones observadas</span><strong>{sessions.length ? Math.round((operableCount / sessions.length) * 100) : 0}% dentro de ventana</strong></div><div className="chart-box small"><ResponsiveContainer width="100%" height="100%"><BarChart data={rangeData} margin={{ top: 8, right: 8, bottom: 0, left: -22 }}><CartesianGrid stroke="#dcd8cd" strokeDasharray="2 5" vertical={false} /><XAxis dataKey="bucket" tickLine={false} axisLine={false} tick={{ fontSize: 10, fill: "#7d8275" }} /><YAxis tickLine={false} axisLine={false} tick={{ fontSize: 10, fill: "#7d8275" }} /><Tooltip contentStyle={{ border: "1px solid #dcd8cd", borderRadius: 8, background: "#fffdf8", fontSize: 12 }} /><Bar dataKey="sessions" fill="#123B66" radius={[4, 4, 0, 0]} /><Bar dataKey="operable" fill="#C51F2A" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer></div><div className="chart-foot"><span><i className="square ink" /> Todas</span><span><i className="square lime" /> Operables</span></div></section></div>
    <div className="lower-grid"><section className="panel timeline-panel"><PanelHeading eyebrow="Event stream" title="Últimos movimientos" action="Ver todos" onClick={() => onView("events")} />{events.length ? <EventTimeline events={events.slice(0, 4)} /> : <CollectionNotice state="empty" error={null} label="eventos" />}</section><section className="panel roadmap-panel" style={{ backgroundImage: `linear-gradient(110deg, rgba(255,253,248,.97), rgba(255,253,248,.86)), url(${LEDGER_TEXTURE})` }}><PanelHeading eyebrow="Implementation / 06" title="Lo que sigue" action="Abrir roadmap" onClick={() => onView("roadmap")} /><div className="roadmap-progress"><span>6 de 6 fases</span><strong>100%</strong></div><div className="progress-track"><div style={{ width: "100%" }} /></div><div className="roadmap-mini"><span className="mini-phase active">05</span><div><strong>PWA de decisión</strong><small>Resumen, métricas y estados vivos</small></div><ChevronRight size={15} /></div><div className="roadmap-mini"><span className="mini-phase active">06</span><div><strong>Canal privado</strong><small>Tailscale Serve · HTTPS read-only</small></div><ChevronRight size={15} /></div></section></div>
  </>;
}

function StrategyView({ onBack }: { onBack: () => void }) { return <ViewFrame eyebrow="Strategy brief" title="London Breakout" description="La estrategia convierte la consolidación asiática en una ventana operable para la apertura europea." onBack={onBack}><div className="module-grid three"><InfoCard icon={Target} title="Filtro de rango" value="15–40 pips" detail="Solo se considera operable cuando el box asiático permanece dentro de esta ventana." /><InfoCard icon={Clock3} title="Ventana" value="Asia → Londres" detail="El sistema mide máximo, mínimo y barras antes de preparar los niveles." /><InfoCard icon={ShieldCheck} title="Modo actual" value="Paper only" detail="El motor observa y simula. No hay órdenes reales habilitadas." /></div><div className="panel detail-sheet"><PanelHeading eyebrow="Execution logic" title="Secuencia de decisión" /><div className="decision-flow"><FlowStep n="01" title="Construir box" text="Capturar la sesión asiática desde IB y registrar su fuente." /><FlowStep n="02" title="Validar rango" text="Comparar pips contra la ventana operable y conservar la evidencia." /><FlowStep n="03" title="Simular breakout" text="Evaluar niveles, break-even, TP y resultado en R." /><FlowStep n="04" title="Auditar" text="Emitir eventos y conservar evidencia del ciclo." /></div></div></ViewFrame>; }
function ConfigView({ health, onBack }: { health: Health; onBack: () => void }) { return <ViewFrame eyebrow="System configuration" title="Configuración operativa" description="Una lectura clara de las reglas y dependencias que condicionan el sistema real." onBack={onBack}><div className="config-grid"><div className="panel detail-sheet"><PanelHeading eyebrow="Strategy parameters" title="Reglas activas" /><ConfigRow label="Instrumento" value="EUR/USD" /><ConfigRow label="Rango mínimo" value="15 pips" /><ConfigRow label="Rango máximo" value="40 pips" /><ConfigRow label="Modo de ejecución" value="Paper / read-only" /><ConfigRow label="Freshness threshold" value={`${health.freshness_threshold_hours || 36} horas`} /></div><div className="panel detail-sheet"><PanelHeading eyebrow="Dependencies" title="Salud de componentes" /><Dependency label="SQLite" value={health.dependencies?.sqlite || "unknown"} icon={Database} /><Dependency label="IB Gateway" value={health.dependencies?.ib_gateway || "unknown"} icon={Radio} /><Dependency label="Cron jobs" value={health.dependencies?.cron || "unknown"} icon={TimerReset} /><Dependency label="Backups" value={health.dependencies?.backup || "unknown"} icon={ShieldCheck} /></div></div></ViewFrame>; }
function CollectionNotice({ state, error, label }: { state: ModuleState; error: string | null; label: string }) { const copy = state === "loading" ? `Consultando ${label}…` : state === "error" ? error || `No se pudo leer ${label}.` : `No hay ${label} registrados todavía.`; return <div className={`collection-notice ${state}`}><span className="mono">{state === "error" ? "LECTURA PENDIENTE" : state === "loading" ? "CARGANDO" : "SIN REGISTROS"}</span><p>{copy}</p></div>; }
function QuickMetric({ label, value, detail, tone }: { label: string; value: string; detail: string; tone?: "positive" | "negative" }) { return <div className="quick-metric"><span>{label}</span><strong className={tone}>{value}</strong><small>{detail}</small></div>; }
function SessionSummary({ sessions }: { sessions: Session[] }) { const latest = sessions[0]; const operable = sessions.filter((session) => session.operable).length; return <section className="session-summary"><QuickMetric label="Última decisión" value={latest?.operable ? "OPERABLE" : "DESCARTAR"} detail={sessionCycleLabel(latest)} tone={latest?.operable ? "positive" : "negative"} /><QuickMetric label="Último rango" value={`${latest?.rango_pips.toFixed(1) || "—"} pips`} detail="ventana 15–40" /><QuickMetric label="Tasa operable" value={`${sessions.length ? Math.round((operable / sessions.length) * 100) : 0}%`} detail={`${operable}/${sessions.length} sesiones`} /></section>; }
function SessionsView({ sessions, state, error, onBack }: { sessions: Session[]; state: ModuleState; error: string | null; onBack: () => void }) { return <ViewFrame eyebrow="Session registry" title="Sesiones asiáticas" description="El registro que alimenta el filtro London Breakout. La decisión y el rango vienen primero; los extremos quedan como evidencia." onBack={onBack}><SessionSummary sessions={sessions} /><div className="view-toolbar"><span>{sessions.length} sesiones cargadas</span><span>Ventana válida: 15–40 pips</span></div><div className="session-list">{sessions.length ? sessions.map((session) => <article className={`session-card ${session.operable ? "operable" : "discard"}`} key={session.fecha}><div className="session-card-top"><span className="mono">{formatDate(session.fecha)}</span><strong className={session.operable ? "positive" : "negative"}>{session.operable ? "OPERABLE" : "DESCARTAR"}</strong></div><div className="session-range"><strong>{session.rango_pips.toFixed(1)} <small>pips</small></strong><span className="range-scale"><i style={{ width: `${Math.min(100, Math.max(8, (session.rango_pips / 40) * 100))}%` }} /></span><small>Ventana 15–40</small></div><div className="session-extremes"><span>Máx <b>{formatPrice(session.maximo)}</b></span><span>Mín <b>{formatPrice(session.minimo)}</b></span></div></article>) : <CollectionNotice state={state} error={error} label="sesiones asiáticas" />}</div></ViewFrame>; }
function PaperView({ trades, state, error, onBack }: { trades: PaperTrade[]; state: ModuleState; error: string | null; onBack: () => void }) { const [period, setPeriod] = useState<Period>("week"); const visibleTrades = useMemo(() => trades.filter((trade) => inPeriod(trade, period)), [trades, period]); const summary = useMemo(() => paperSummary(visibleTrades), [visibleTrades]); const winRate = summary.closed ? Math.round((summary.won / summary.closed) * 100) : 0; return <ViewFrame eyebrow="Paper trading lab" title="Resultados del agente" description="R realizado separado de resultados pendientes al corte de las 11:00 y de sesiones descartadas." onBack={onBack}><div className="period-tabs" role="tablist" aria-label="Periodo de paper trading">{PERIODS.map((item) => <button key={item.id} role="tab" aria-selected={period === item.id} className={period === item.id ? "active" : ""} onClick={() => setPeriod(item.id)}>{item.label}</button>)}</div><div className="metric-strip inner"><Metric icon={TrendingUp} label="R realizado" value={formatR(summary.realizedR)} note={`${summary.closed} cierres confirmados`} tone={summary.realizedR < 0 ? "red" : "lime"} /><Metric icon={CheckCircle2} label="Tasa de acierto" value={`${winRate}%`} note={`${summary.won} TP / ${summary.lost} SL`} /><Metric icon={ShieldCheck} label="Al corte 11:00" value={`${summary.unresolved}`} note="R no realizado" tone="amber" /><Metric icon={Target} label="SKIP" value={`${summary.skipped}`} note="sesiones no operables" /></div><section className="paper-legend"><span><i className="legend-dot closed" /> R realizado: TP, SL o cierre confirmado</span><span><i className="legend-dot cutoff" /> Al corte 11:00: R observado, no incluido</span></section><div className="paper-list">{visibleTrades.length ? visibleTrades.map((trade, index) => { const cutoff = isAtCutoff(trade); const skipped = isSkipped(trade); const r = Number(trade.r ?? trade.r_multiple ?? 0); return <article className={`paper-row ${cutoff ? "cutoff" : skipped ? "skipped" : r < 0 ? "loss" : "win"}`} key={`${trade.fecha}-${index}`}><div className="paper-date"><span>{formatDate(trade.fecha || trade.date)}</span><small>{tradeDirection(trade)}</small></div><div><strong>{tradeStatusLabel(trade)}</strong><small>{cutoff ? "R observado · no realizado" : skipped ? "Sin operación" : "Cierre confirmado"}</small></div><div className={`paper-r ${cutoff ? "warning-text" : r >= 0 ? "positive" : "negative"}`}>{formatR(r)}</div><div className="mono paper-levels">E {formatPrice(trade.entry)} · SL {formatPrice(trade.sl)} · TP {formatPrice(trade.tp)}</div></article>; }) : <CollectionNotice state={state} error={error} label="paper trades en este periodo" />}</div></ViewFrame>; }
function EventsView({ events, state, error, onBack }: { events: EventItem[]; state: ModuleState; error: string | null; onBack: () => void }) { const decisions = events.filter((event) => event.event.includes("PAPER") || event.event.includes("SESSION")); return <ViewFrame eyebrow="Traceability log" title="Línea temporal" description="Las decisiones de estrategia se priorizan; la ejecución de jobs conserva la evidencia auditada." onBack={onBack}><div className="event-summary"><QuickMetric label="Decisiones" value={`${decisions.length}`} detail="sesión o paper trade" /><QuickMetric label="Eventos" value={`${events.length}`} detail="trazabilidad visible" /><QuickMetric label="Último ciclo" value={formatDate(events[0]?.session_date)} detail={events[0]?.event.replaceAll("_", " ") || "—"} /></div><div className="event-view-grid"><div className="panel timeline-panel full">{events.length ? <EventTimeline events={events} /> : <CollectionNotice state={state} error={error} label="eventos" />}</div><div className="event-aside"><div className="aside-callout"><Sparkles size={18} /><strong>Read-only by design</strong><p>Esta consola observa el sistema. No hay endpoints de escritura ni ejecución real habilitada.</p></div><div className="aside-stat"><span>Eventos visibles</span><strong>{events.length}</strong></div><div className="aside-stat"><span>Última fuente</span><strong>{events[0]?.source || "—"}</strong></div></div></div></ViewFrame>; }
function RoadmapView({ onBack }: { onBack: () => void }) { return <ViewFrame eyebrow="Implementation plan" title="Roadmap de construcción" description="La plataforma ya observa datos reales; las siguientes mejoras priorizan interpretación y uso consistente." onBack={onBack}><div className="roadmap-list">{roadmap.map((item) => <div className={`roadmap-row ${item.status}`} key={item.phase}><div className="roadmap-number">{item.phase}</div><div className="roadmap-copy"><strong>{item.title}</strong><span>{item.detail}</span></div><div className={`roadmap-status ${item.status}`}>{item.status === "done" ? "COMPLETADA" : item.status === "active" ? "EN CURSO" : "SIGUIENTE"}</div><ChevronRight size={16} /></div>)}</div></ViewFrame>; }
function LiveView({ onBack }: { onBack: () => void }) { return <ViewFrame eyebrow="Real trading gate" title="Trading real" description="Este módulo documenta el futuro canal de ejecución, pero permanece bloqueado hasta completar controles adicionales." onBack={onBack}><div className="live-gate"><div className="live-gate-icon"><LockKeyhole size={32} /></div><div><Badge className="badge-warning">BLOQUEADO POR DISEÑO</Badge><h2>Sin órdenes reales habilitadas</h2><p>Para desbloquear esta zona todavía faltan autenticación fuerte, doble confirmación, límites de riesgo, auditoría de órdenes y una decisión explícita sobre el canal seguro hacia IB Gateway.</p></div></div><div className="module-grid three"><InfoCard icon={ShieldCheck} title="Control de riesgo" value="Pendiente" detail="Límites diarios, tamaño y kill switch." /><InfoCard icon={LockKeyhole} title="Autorización" value="Pendiente" detail="Separar lectura, simulación y ejecución." /><InfoCard icon={ListTree} title="Auditoría" value="Pendiente" detail="Registrar cada intención y resultado." /></div></ViewFrame>; }
function ViewFrame({ eyebrow, title, description, onBack, children }: { eyebrow: string; title: string; description: string; onBack: () => void; children: ReactNode }) { return <><div className="page-intro"><div><div className="section-kicker"><span className="kicker-line" /> {eyebrow}</div><h1>{title}</h1><p>{description}</p></div><Button variant="outline" onClick={onBack}><LayoutDashboard size={15} /> Resumen</Button></div>{children}</>; }
function Metric({ icon: Icon, label, value, note, tone = "ink" }: { icon: typeof Activity; label: string; value: string; note: string; tone?: string }) { return <div className="metric"><div className={`metric-icon ${tone}`}><Icon size={16} /></div><div><span>{label}</span><strong>{value}</strong><small>{note}</small></div></div>; }
function PanelHeading({ eyebrow, title, action, onClick }: { eyebrow: string; title: string; action?: string; onClick?: () => void }) { return <div className="panel-heading"><div><div className="panel-eyebrow">{eyebrow}</div><h2>{title}</h2></div>{onClick && <button onClick={onClick}>{action}<ArrowUpRight size={14} /></button>}</div>; }
function EventTimeline({ events }: { events: EventItem[] }) { return <div className="timeline">{events.map((item) => { const direction = item.r_multiple == null ? "" : item.r_multiple >= 0 ? "positive" : "negative"; return <div className={`timeline-item ${direction}`} key={`${item.id}-${item.timestamp}`}><div className="timeline-rail"><span className="timeline-dot" /></div><div className="timeline-body"><div className="timeline-top"><strong>{item.event.replaceAll("_", " ")}</strong><span>{formatTime(item.timestamp)}</span></div><p>{item.source} · {item.session_date}{item.direction ? ` · ${item.direction}` : ""}</p>{item.r_multiple != null && <Badge className={item.r_multiple >= 0 ? "badge-positive" : "badge-negative"}>{formatR(item.r_multiple)}</Badge>}</div></div>; })}</div>; }
function InfoCard({ icon: Icon, title, value, detail }: { icon: typeof Activity; title: string; value: string; detail: string }) { return <div className="panel info-card"><Icon size={19} /><div><span>{title}</span><strong>{value}</strong><p>{detail}</p></div></div>; }
function FlowStep({ n, title, text }: { n: string; title: string; text: string }) { return <div className="flow-step"><span>{n}</span><div><strong>{title}</strong><p>{text}</p></div></div>; }
function ConfigRow({ label, value }: { label: string; value: string }) { return <div className="config-row"><span>{label}</span><strong>{value}</strong></div>; }
function Dependency({ label, value, icon: Icon }: { label: string; value: string; icon: typeof Activity }) { const good = value.toLowerCase().includes("healthy"); return <div className="dependency"><Icon size={16} /><span>{label}</span><strong className={good ? "positive" : "warning-text"}>{value}</strong></div>; }
