// Design philosophy: Control Room Editorial x WhatsApp utility — tinta petróleo, marfil, señales lime y navegación móvil por conversaciones operativas.
import { useEffect, useMemo, useRef, useState, type ReactNode, type TouchEvent } from "react";
import {
  Activity, ArrowUpRight, BarChart3, Bell, BookOpen, CalendarDays, CheckCircle2,
  ChevronRight, CircleDot, Clock3, Database, GitBranch, LayoutDashboard, LineChart,
  ListTree, LockKeyhole, Menu, Radio, RefreshCw, Settings2, ShieldCheck, Sparkles,
  Target, TimerReset, TrendingUp, X, Zap,
} from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

const MONOGRAM = "/manus-storage/london-bos-monogram-red-blue_db524507.png";
const CONTROL_ROOM = "/manus-storage/london-bos-control-room_3a48b6ed.jpg";
const LEDGER_TEXTURE = "/manus-storage/london-bos-ledger-texture_db4ff039.jpg";
const API_URL = import.meta.env.VITE_LONDON_BOS_API_URL || "";

type View = "overview" | "strategy" | "config" | "sessions" | "paper" | "events" | "roadmap" | "live";
const VIEW_ORDER: View[] = ["overview", "strategy", "config", "sessions", "paper", "events", "roadmap", "live"];
type ConnectionState = "demo" | "live" | "offline" | "stale";
type Session = { fecha: string; maximo: number; minimo: number; rango_pips: number; operable: boolean };
type EventItem = { id: number; event: string; timestamp: string; source: string; session_date: string; direction?: string | null; price?: number | null; r_multiple?: number | null; metadata?: Record<string, unknown> | null; metadata_legacy?: string | null };
type PaperTrade = { fecha?: string; date?: string; direccion?: string; direction?: string; salida?: string; exit?: string; r?: number; r_multiple?: number; entry?: number; sl?: number; tp?: number };
type Health = { data_status?: "fresh" | "stale" | "unknown"; api_status?: string; dependency_status?: string; last_session_date?: string; last_sesion_date?: string; data_age_hours?: number; freshness_threshold_hours?: number; dependencies?: Record<string, string> };

const demoSessions: Session[] = [
  { fecha: "2026-08-19", maximo: 1.15968, minimo: 1.15737, rango_pips: 23.1, operable: true },
  { fecha: "2026-08-16", maximo: 1.15942, minimo: 1.15738, rango_pips: 20.5, operable: true },
  { fecha: "2026-08-13", maximo: 1.15441, minimo: 1.15322, rango_pips: 12, operable: false },
  { fecha: "2026-08-12", maximo: 1.15314, minimo: 1.15118, rango_pips: 19.5, operable: true },
  { fecha: "2026-08-11", maximo: 1.15447, minimo: 1.15322, rango_pips: 12.5, operable: false },
];
const demoEvents: EventItem[] = [
  { id: 10, event: "PAPER_TRADE_COMPLETED", timestamp: "2026-08-19T11:00:00-05:00", source: "paper_trade", session_date: "2026-08-19", direction: "BUY", r_multiple: 1.5 },
  { id: 9, event: "JOB_COMPLETED", timestamp: "2026-08-19T11:00:00-05:00", source: "paper-end", session_date: "2026-08-19" },
  { id: 8, event: "PAPER_TRADE_SNAPSHOT", timestamp: "2026-08-19T04:30:00-05:00", source: "paper-mid", session_date: "2026-08-19", direction: "BUY", r_multiple: 0.3 },
  { id: 7, event: "SESSION_RECORDED", timestamp: "2026-08-19T01:50:00-05:00", source: "fx_session", session_date: "2026-08-19" },
];
const demoPaper: PaperTrade[] = [
  { fecha: "2026-08-19", direccion: "BUY", salida: "TP", r: 1.5, entry: 1.15968, sl: 1.15768, tp: 1.16268 },
  { fecha: "2026-08-16", direccion: "BUY", salida: "ABIERTA_11H", r: 0.3, entry: 1.15942, sl: 1.15742, tp: 1.16242 },
];
const performanceData = [{ day: "13 Jul", r: 1.5 }, { day: "20 Jul", r: 0.5 }, { day: "23 Jul", r: 2 }, { day: "29 Jul", r: 1.86 }, { day: "06 Aug", r: 2.19 }, { day: "13 Aug", r: 2.09 }, { day: "19 Aug", r: 3.93 }];
const rangeData = [{ bucket: "<15", sessions: 2, operable: 0 }, { bucket: "15–20", sessions: 3, operable: 3 }, { bucket: "20–30", sessions: 5, operable: 5 }, { bucket: "30–40", sessions: 2, operable: 2 }, { bucket: ">40", sessions: 1, operable: 0 }];
const roadmap = [
  { phase: "01", title: "Seguridad y saneamiento", detail: "Secretos, DB y logs fuera de Git", status: "done" },
  { phase: "02", title: "Dominio común", detail: "Contratos y reglas puras compartidas", status: "done" },
  { phase: "03", title: "API read-only", detail: "Health, sesiones, paper trades y eventos", status: "done" },
  { phase: "04", title: "Observabilidad endurecida", detail: "Freshness, idempotencia y metadata JSON", status: "done" },
  { phase: "05", title: "PWA operativa", detail: "Dashboard móvil, navegación y estados vivos", status: "active" },
  { phase: "06", title: "Canal privado", detail: "VPN o túnel HTTPS autenticado", status: "next" },
];

function formatDate(value?: string) { return value ? new Intl.DateTimeFormat("es-ES", { day: "2-digit", month: "short" }).format(new Date(value)) : "—"; }
function formatTime(value?: string) { return value ? new Intl.DateTimeFormat("es-ES", { hour: "2-digit", minute: "2-digit" }).format(new Date(value)) : "—"; }
function formatPrice(value?: number | null) { return value == null ? "—" : value.toFixed(5); }
async function fetchJson<T>(path: string): Promise<T> { const response = await fetch(`${API_URL}${path}`, { headers: { Accept: "application/json" } }); if (!response.ok) throw new Error(`HTTP ${response.status}`); return response.json() as Promise<T>; }
function StatusPill({ state }: { state: ConnectionState }) { const copy = state === "live" ? "API LIVE" : state === "stale" ? "API STALE" : state === "offline" ? "API OFFLINE" : "MODO DEMO"; return <span className={`status-pill ${state}`}><span className="status-dot" />{copy}</span>; }

export default function Home() {
  const [view, setView] = useState<View>("overview"); const [mobileOpen, setMobileOpen] = useState(false); const [isMobileApp, setIsMobileApp] = useState(false); const [viewDirection, setViewDirection] = useState<"forward" | "back">("forward"); const touchStart = useRef<{ x: number; y: number } | null>(null);
  const [sessions, setSessions] = useState(demoSessions); const [events, setEvents] = useState(demoEvents); const [paperTrades, setPaperTrades] = useState(demoPaper);
  const [connection, setConnection] = useState<ConnectionState>("demo"); const [health, setHealth] = useState<Health>({}); const [lastSync, setLastSync] = useState("demo local · sin endpoint configurado");
  const refresh = async () => { if (!API_URL) { setConnection("demo"); return; } try { const [s, e, p, h] = await Promise.all([fetchJson<{ data: Session[] }>("/api/session/history?limit=30"), fetchJson<{ data: EventItem[] }>("/api/events?limit=50"), fetchJson<{ data: PaperTrade[] }>("/api/paper-trades?limit=30"), fetchJson<Health>("/api/health")]); setSessions(s.data || []); setEvents(e.data || []); setPaperTrades(p.data || []); setHealth(h); setConnection(h.data_status === "stale" ? "stale" : "live"); setLastSync(new Intl.DateTimeFormat("es-ES", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" }).format(new Date())); } catch { setConnection("offline"); setLastSync("último intento fallido"); } };
  useEffect(() => { const query = window.matchMedia("(max-width: 760px)"); const detect = () => setIsMobileApp(query.matches || (navigator.maxTouchPoints > 0 && window.matchMedia("(pointer: coarse)").matches)); detect(); query.addEventListener?.("change", detect); return () => query.removeEventListener?.("change", detect); }, []);
  useEffect(() => { refresh(); const timer = window.setInterval(refresh, 30000); return () => window.clearInterval(timer); }, []);
  const operableCount = sessions.filter((item) => item.operable).length; const avgRange = sessions.length ? sessions.reduce((sum, item) => sum + item.rango_pips, 0) / sessions.length : 0;
  const navItems = [{ id: "overview" as View, label: "Resumen", icon: LayoutDashboard }, { id: "strategy" as View, label: "Estrategia", icon: BookOpen }, { id: "config" as View, label: "Configuración", icon: Settings2 }, { id: "sessions" as View, label: "Sesiones", icon: CalendarDays }, { id: "paper" as View, label: "Paper trading", icon: TrendingUp }, { id: "events" as View, label: "Eventos", icon: ListTree }, { id: "roadmap" as View, label: "Roadmap", icon: GitBranch }, { id: "live" as View, label: "Trading real", icon: LockKeyhole }];
  const title = navItems.find((item) => item.id === view)?.label || "Resumen";
  const moveTo = (next: View) => { if (next === view) return; setViewDirection(VIEW_ORDER.indexOf(next) >= VIEW_ORDER.indexOf(view) ? "forward" : "back"); setView(next); setMobileOpen(false); };
  const handleTouchStart = (event: TouchEvent<HTMLElement>) => { const target = event.target as HTMLElement; if (target.closest("button, a, input, textarea, select")) return; const touch = event.touches[0]; touchStart.current = touch ? { x: touch.clientX, y: touch.clientY } : null; };
  const handleTouchEnd = (event: TouchEvent<HTMLElement>) => { if (!isMobileApp || !touchStart.current) return; const touch = event.changedTouches[0]; const dx = touch.clientX - touchStart.current.x; const dy = touch.clientY - touchStart.current.y; touchStart.current = null; if (Math.abs(dx) < 72 || Math.abs(dx) < Math.abs(dy) * 1.35) return; const current = VIEW_ORDER.indexOf(view); const nextIndex = dx < 0 ? Math.min(VIEW_ORDER.length - 1, current + 1) : Math.max(0, current - 1); if (nextIndex !== current) moveTo(VIEW_ORDER[nextIndex]); };
  return <div className={`dashboard-shell ${isMobileApp ? "mobile-app-mode" : "desktop-console-mode"}`}>
    <aside className={`app-sidebar ${mobileOpen ? "open" : ""}`}><div className="brand-lockup"><div className="brand-mark"><img src={MONOGRAM} alt="London-BOS" /></div><div><div className="brand-name">LONDON<span>·</span>BOS</div><div className="brand-kicker">OPERATIONS CONSOLE</div></div><button className="mobile-close" onClick={() => setMobileOpen(false)} aria-label="Cerrar menú"><X size={18} /></button></div><div className="sidebar-rule" /><div className="nav-label">Espacio de trabajo</div><nav className="main-nav" aria-label="Navegación principal">{navItems.map(({ id, label, icon: Icon }) => <button key={id} className={view === id ? "active" : ""} onClick={() => moveTo(id)}><Icon size={17} /><span>{label}</span>{view === id && <ChevronRight size={14} className="nav-arrow" />}</button>)}</nav><div className="sidebar-spacer" /><div className="sidebar-status"><div className="sidebar-status-head"><span>System status</span><ShieldCheck size={15} /></div><StatusPill state={connection} /><div className="sidebar-status-copy">Read-only by design. La ejecución real permanece bloqueada.</div></div><div className="sidebar-footer"><span>v0.3.0 PWA</span><span>19 · 08 · 26</span></div></aside>
    {mobileOpen && <button className="mobile-overlay" onClick={() => setMobileOpen(false)} aria-label="Cerrar menú" />}
    <main className="main-canvas"><div className="mobile-app-strip"><div className="mobile-app-brand"><img src={MONOGRAM} alt="" /><div><strong>LONDON·BOS</strong><span>Conversación operativa</span></div></div><div className="mobile-app-actions"><StatusPill state={connection} /><button className="mobile-app-menu" onClick={() => setMobileOpen(true)} aria-label="Abrir módulos"><Menu size={19} /></button></div></div><header className="topbar"><div className="topbar-left"><button className="mobile-menu" onClick={() => setMobileOpen(true)} aria-label="Abrir menú"><Menu size={20} /></button><span className="eyebrow">LONDON-BOS / {title.toUpperCase()}</span></div><div className="topbar-actions"><span className="sync-label"><span className="sync-pulse" /> {lastSync}</span><Button variant="outline" size="sm" onClick={refresh} className="refresh-button"><RefreshCw size={14} /> Actualizar</Button><button className="icon-button" aria-label="Notificaciones"><Bell size={17} /><span /></button></div></header>
      <section key={view} className={`content-wrap view-stage ${viewDirection}`} onTouchStart={handleTouchStart} onTouchEnd={handleTouchEnd}>{view === "overview" && <Overview sessions={sessions} events={events} avgRange={avgRange} operableCount={operableCount} connection={connection} health={health} onView={moveTo} />}{view === "strategy" && <StrategyView onBack={() => moveTo("overview")} />}{view === "config" && <ConfigView health={health} onBack={() => moveTo("overview")} />}{view === "sessions" && <SessionsView sessions={sessions} onBack={() => moveTo("overview")} />}{view === "paper" && <PaperView trades={paperTrades} onBack={() => moveTo("overview")} />}{view === "events" && <EventsView events={events} onBack={() => moveTo("overview")} />}{view === "roadmap" && <RoadmapView onBack={() => moveTo("overview")} />}{view === "live" && <LiveView onBack={() => moveTo("overview")} />}</section>
    </main><nav className="mobile-bottom-nav" aria-label="Navegación móvil"><button className={view === "overview" ? "active" : ""} onClick={() => moveTo("overview")}><LayoutDashboard size={18} /><span>Resumen</span></button><button className={view === "sessions" ? "active" : ""} onClick={() => moveTo("sessions")}><CalendarDays size={18} /><span>Sesiones</span></button><button className={view === "paper" ? "active" : ""} onClick={() => moveTo("paper")}><TrendingUp size={18} /><span>Paper</span></button><button className={view === "events" ? "active" : ""} onClick={() => moveTo("events")}><ListTree size={18} /><span>Eventos</span></button></nav></div>;
}

function Overview({ sessions, events, avgRange, operableCount, connection, health, onView }: { sessions: Session[]; events: EventItem[]; avgRange: number; operableCount: number; connection: ConnectionState; health: Health; onView: (v: View) => void }) { const latest = sessions[0]; return <><section className="mobile-inbox" aria-label="Bandejas operativas"><div className="mobile-inbox-heading"><div><span className="panel-eyebrow">Bandeja operativa</span><h2>London-BOS</h2></div><span className="mobile-unread">{events.length || 0}</span></div><button className="mobile-thread" onClick={() => onView("sessions")}><span className="thread-avatar thread-red"><CalendarDays size={18} /></span><span className="thread-copy"><strong>Sesión Londres</strong><small>{latest?.operable ? "Dentro de rango · señal operable" : "Última sesión revisada"}</small></span><span className="thread-meta"><b>{latest ? formatDate(latest.fecha) : "—"}</b><ChevronRight size={16} /></span></button><button className="mobile-thread" onClick={() => onView("paper")}><span className="thread-avatar thread-blue"><TrendingUp size={18} /></span><span className="thread-copy"><strong>Paper trading</strong><small>Resultado y curva del ciclo observado</small></span><span className="thread-meta"><b>+3.93R</b><ChevronRight size={16} /></span></button><button className="mobile-thread" onClick={() => onView("events")}><span className="thread-avatar thread-ink"><ListTree size={18} /></span><span className="thread-copy"><strong>Eventos del sistema</strong><small>{connection === "demo" ? "Vista local · sin endpoint" : "Últimos eventos recibidos"}</small></span><span className="thread-meta"><b>{events.length}</b><ChevronRight size={16} /></span></button></section>
  <section className="hero-panel" style={{ backgroundImage: `linear-gradient(90deg, rgba(244,241,232,.98) 0%, rgba(244,241,232,.87) 42%, rgba(244,241,232,.36) 100%), url(${CONTROL_ROOM})` }}><div className="hero-copy"><div className="section-kicker"><span className="kicker-line" /> INFORME OPERATIVO DIARIO</div><h1>La sesión<br /><em>{latest?.operable ? "está dentro de rango." : "está fuera de rango."}</em></h1><p>Una consola móvil para entender el sistema, verificar sus señales y seguir cada decisión sin tocar la ejecución.</p><div className="hero-meta"><span><Clock3 size={14} /> Última sesión · {formatDate(latest?.fecha)}</span><span><Radio size={14} /> EUR/USD · London Breakout</span></div></div><div className="hero-evidence"><span>LB / LIVE BOARD</span><span>SOURCE · IB + SQLITE</span><span>MODE · READ ONLY</span></div><div className="hero-signal"><div className="signal-ring"><div className="signal-core"><span>{latest?.rango_pips?.toFixed(1) || "—"}</span><small>PIPS</small></div></div><div className="signal-caption"><span className="signal-mark">{latest?.operable ? "✓" : "!"}</span><div><strong>{latest?.operable ? "OPERABLE" : "DESCARTAR"}</strong><small>Ventana válida 15–40 pips</small></div></div></div></section>
  <section className="metric-strip"><Metric icon={Activity} label="Estado datos" value={connection === "live" ? "FRESH" : connection === "stale" ? "STALE" : connection === "offline" ? "OFFLINE" : "DEMO"} note={health.data_age_hours ? `${health.data_age_hours.toFixed(1)}h de antigüedad` : "sin endpoint"} tone={connection === "stale" ? "amber" : "lime"} /><Metric icon={Target} label="Rango medio" value={`${avgRange.toFixed(1)} pips`} note="últimas sesiones" /><Metric icon={Zap} label="Operable" value={`${operableCount}/${sessions.length}`} note="sesiones en zona" tone="lime" /><Metric icon={LineChart} label="Paper acumulado" value="+3.93R" note="ciclo observado" tone="blue" /></section>
  <div className="overview-grid"><section className="panel performance-panel"><PanelHeading eyebrow="Paper trading / equity" title="La curva de aprendizaje" action="Abrir paper" onClick={() => onView("paper")} /><div className="chart-legend"><span><i className="legend-line" /> Equity acumulada en R</span><span className="muted-legend">último ciclo · +3.93R</span></div><div className="chart-box"><ResponsiveContainer width="100%" height="100%"><AreaChart data={performanceData} margin={{ top: 8, right: 8, bottom: 0, left: -22 }}><defs><linearGradient id="equityFillPwa" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#B7D83D" stopOpacity={0.4} /><stop offset="100%" stopColor="#B7D83D" stopOpacity={0.02} /></linearGradient></defs><CartesianGrid stroke="#dcd8cd" strokeDasharray="2 5" vertical={false} /><XAxis dataKey="day" tickLine={false} axisLine={false} tick={{ fontSize: 10, fill: "#7d8275" }} /><YAxis tickLine={false} axisLine={false} tick={{ fontSize: 10, fill: "#7d8275" }} /><Tooltip contentStyle={{ border: "1px solid #dcd8cd", borderRadius: 8, background: "#fffdf8", fontSize: 12 }} /><Area type="monotone" dataKey="r" stroke="#12343B" strokeWidth={2.5} fill="url(#equityFillPwa)" /></AreaChart></ResponsiveContainer></div></section><section className="panel range-panel"><PanelHeading eyebrow="Session filter" title="Dónde está la señal" action="Abrir sesiones" onClick={() => onView("sessions")} /><div className="chart-annotation"><span>{sessions.length} sesiones observadas</span><strong>{sessions.length ? Math.round((operableCount / sessions.length) * 100) : 0}% dentro de ventana</strong></div><div className="chart-box small"><ResponsiveContainer width="100%" height="100%"><BarChart data={rangeData} margin={{ top: 8, right: 8, bottom: 0, left: -22 }}><CartesianGrid stroke="#dcd8cd" strokeDasharray="2 5" vertical={false} /><XAxis dataKey="bucket" tickLine={false} axisLine={false} tick={{ fontSize: 10, fill: "#7d8275" }} /><YAxis tickLine={false} axisLine={false} tick={{ fontSize: 10, fill: "#7d8275" }} /><Tooltip contentStyle={{ border: "1px solid #dcd8cd", borderRadius: 8, background: "#fffdf8", fontSize: 12 }} /><Bar dataKey="sessions" fill="#12343B" radius={[4, 4, 0, 0]} /><Bar dataKey="operable" fill="#B7D83D" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer></div><div className="chart-foot"><span><i className="square ink" /> Todas</span><span><i className="square lime" /> Operables</span></div></section></div>
  <div className="lower-grid"><section className="panel timeline-panel"><PanelHeading eyebrow="Event stream" title="Últimos movimientos" action="Ver todos" onClick={() => onView("events")} /><EventTimeline events={events.slice(0, 4)} /></section><section className="panel roadmap-panel" style={{ backgroundImage: `linear-gradient(110deg, rgba(255,253,248,.97), rgba(255,253,248,.86)), url(${LEDGER_TEXTURE})` }}><PanelHeading eyebrow="Implementation / 05" title="Lo que sigue" action="Abrir roadmap" onClick={() => onView("roadmap")} /><div className="roadmap-progress"><span>5 de 6 fases</span><strong>83%</strong></div><div className="progress-track"><div style={{ width: "83%" }} /></div><div className="roadmap-mini"><span className="mini-phase active">05</span><div><strong>PWA operativa</strong><small>Experiencia móvil, módulos y estados vivos</small></div><ChevronRight size={15} /></div><div className="roadmap-mini"><span className="mini-phase">06</span><div><strong>Canal privado</strong><small>VPN o túnel HTTPS autenticado</small></div><ChevronRight size={15} /></div></section></div>
</>; }

function StrategyView({ onBack }: { onBack: () => void }) { return <ViewFrame eyebrow="Strategy brief" title="London Breakout" description="La estrategia convierte la consolidación asiática en una ventana operable para la apertura europea." onBack={onBack}><div className="module-grid three"><InfoCard icon={Target} title="Filtro de rango" value="15–40 pips" detail="Solo se considera operable cuando el box asiático permanece dentro de esta ventana." /><InfoCard icon={Clock3} title="Ventana" value="Asia → Londres" detail="El sistema mide máximo, mínimo y barras antes de preparar los niveles." /><InfoCard icon={ShieldCheck} title="Modo actual" value="Paper only" detail="El motor observa y simula. No hay órdenes reales habilitadas." /></div><div className="panel detail-sheet"><PanelHeading eyebrow="Execution logic" title="Secuencia de decisión" /><div className="decision-flow"><FlowStep n="01" title="Construir box" text="Capturar la sesión asiática desde IB y registrar su fuente." /><FlowStep n="02" title="Validar rango" text="Comparar pips contra la ventana operable y conservar la evidencia." /><FlowStep n="03" title="Simular breakout" text="Evaluar niveles, break-even, TP y resultado en R." /><FlowStep n="04" title="Auditar" text="Emitir eventos y enviar el mensaje operativo previsto." /></div></div></ViewFrame>; }
function ConfigView({ health, onBack }: { health: Health; onBack: () => void }) { return <ViewFrame eyebrow="System configuration" title="Configuración operativa" description="Una lectura clara de las reglas y dependencias que condicionan el sistema real." onBack={onBack}><div className="config-grid"><div className="panel detail-sheet"><PanelHeading eyebrow="Strategy parameters" title="Reglas activas" /><ConfigRow label="Instrumento" value="EUR/USD" /><ConfigRow label="Rango mínimo" value="15 pips" /><ConfigRow label="Rango máximo" value="40 pips" /><ConfigRow label="Modo de ejecución" value="Paper / read-only" /><ConfigRow label="Freshness threshold" value={`${health.freshness_threshold_hours || 36} horas`} /></div><div className="panel detail-sheet"><PanelHeading eyebrow="Dependencies" title="Salud de componentes" /><Dependency label="SQLite" value={health.dependencies?.sqlite || "unknown"} icon={Database} /><Dependency label="IB Gateway" value={health.dependencies?.ib_gateway || "unknown"} icon={Radio} /><Dependency label="Cron jobs" value={health.dependencies?.cron || "unknown"} icon={TimerReset} /><Dependency label="Backups" value={health.dependencies?.backup || "unknown"} icon={ShieldCheck} /></div></div></ViewFrame>; }
function SessionsView({ sessions, onBack }: { sessions: Session[]; onBack: () => void }) { return <ViewFrame eyebrow="Session registry" title="Sesiones asiáticas" description="El registro que alimenta el filtro London Breakout. Cada fila conserva la evidencia de su decisión." onBack={onBack}><div className="view-toolbar"><span>{sessions.length} sesiones cargadas</span><span>Ventana válida: 15–40 pips</span></div><div className="data-table"><div className="data-row data-head"><span>Fecha</span><span>Máximo</span><span>Mínimo</span><span>Rango</span><span>Decisión</span></div>{sessions.map((session) => <div className="data-row" key={session.fecha}><span className="mono">{formatDate(session.fecha)}</span><span className="mono">{formatPrice(session.maximo)}</span><span className="mono">{formatPrice(session.minimo)}</span><span className="mono">{session.rango_pips.toFixed(1)} pips</span><span className={session.operable ? "decision positive" : "decision negative"}>{session.operable ? "OPERABLE" : "DESCARTAR"}</span></div>)}</div></ViewFrame>; }
function PaperView({ trades, onBack }: { trades: PaperTrade[]; onBack: () => void }) { const total = trades.reduce((sum, trade) => sum + Number(trade.r ?? trade.r_multiple ?? 0), 0); return <ViewFrame eyebrow="Paper trading lab" title="Resultados del agente" description="La bitácora de simulación antes de cualquier conversación sobre ejecución real." onBack={onBack}><div className="metric-strip inner"><Metric icon={TrendingUp} label="Resultado acumulado" value={`${total >= 0 ? "+" : ""}${total.toFixed(2)}R`} note="muestra cargada" tone="lime" /><Metric icon={CheckCircle2} label="Trades visibles" value={`${trades.length}`} note="sin órdenes reales" /><Metric icon={ShieldCheck} label="Control" value="BLOQUEADO" note="paper only" tone="blue" /></div><div className="paper-list">{trades.map((trade, index) => <div className="paper-row" key={`${trade.fecha}-${index}`}><div className="paper-date"><span>{formatDate(trade.fecha || trade.date)}</span><small>{trade.direccion || trade.direction || "—"}</small></div><div><strong>{trade.salida || trade.exit || "—"}</strong><small>Resultado de sesión</small></div><div className={`paper-r ${(trade.r ?? trade.r_multiple ?? 0) >= 0 ? "positive" : "negative"}`}>{(trade.r ?? trade.r_multiple ?? 0) >= 0 ? "+" : ""}{Number(trade.r ?? trade.r_multiple ?? 0).toFixed(2)}R</div><div className="mono paper-levels">E {formatPrice(trade.entry)} · SL {formatPrice(trade.sl)} · TP {formatPrice(trade.tp)}</div></div>)}</div></ViewFrame>; }
function EventsView({ events, onBack }: { events: EventItem[]; onBack: () => void }) { return <ViewFrame eyebrow="Traceability log" title="Línea temporal" description="Cada evento explica qué hizo el sistema, cuándo lo hizo y con qué fuente." onBack={onBack}><div className="event-view-grid"><div className="panel timeline-panel full"><EventTimeline events={events} /></div><div className="event-aside"><div className="aside-callout"><Sparkles size={18} /><strong>Read-only by design</strong><p>Esta consola observa el sistema. No hay endpoints de escritura ni ejecución real habilitada.</p></div><div className="aside-stat"><span>Eventos visibles</span><strong>{events.length}</strong></div><div className="aside-stat"><span>Última fuente</span><strong>{events[0]?.source || "—"}</strong></div></div></div></ViewFrame>; }
function RoadmapView({ onBack }: { onBack: () => void }) { return <ViewFrame eyebrow="Implementation plan" title="Roadmap de construcción" description="Una ruta concreta para pasar de observación local a una plataforma modular, instalable y auditable." onBack={onBack}><div className="roadmap-list">{roadmap.map((item) => <div className={`roadmap-row ${item.status}`} key={item.phase}><div className="roadmap-number">{item.phase}</div><div className="roadmap-copy"><strong>{item.title}</strong><span>{item.detail}</span></div><div className={`roadmap-status ${item.status}`}>{item.status === "done" ? "COMPLETADA" : item.status === "active" ? "EN CURSO" : "SIGUIENTE"}</div><ChevronRight size={16} /></div>)}</div></ViewFrame>; }
function LiveView({ onBack }: { onBack: () => void }) { return <ViewFrame eyebrow="Real trading gate" title="Trading real" description="Este módulo documenta el futuro canal de ejecución, pero permanece bloqueado hasta completar controles adicionales." onBack={onBack}><div className="live-gate"><div className="live-gate-icon"><LockKeyhole size={32} /></div><div><Badge className="badge-warning">BLOQUEADO POR DISEÑO</Badge><h2>Sin órdenes reales habilitadas</h2><p>Para desbloquear esta zona todavía faltan autenticación fuerte, doble confirmación, límites de riesgo, auditoría de órdenes y una decisión explícita sobre el canal seguro hacia IB Gateway.</p></div></div><div className="module-grid three"><InfoCard icon={ShieldCheck} title="Control de riesgo" value="Pendiente" detail="Límites diarios, tamaño y kill switch." /><InfoCard icon={LockKeyhole} title="Autorización" value="Pendiente" detail="Separar lectura, simulación y ejecución." /><InfoCard icon={ListTree} title="Auditoría" value="Pendiente" detail="Registrar cada intención y resultado." /></div></ViewFrame>; }
function ViewFrame({ eyebrow, title, description, onBack, children }: { eyebrow: string; title: string; description: string; onBack: () => void; children: ReactNode }) { return <><div className="page-intro"><div><div className="section-kicker"><span className="kicker-line" /> {eyebrow}</div><h1>{title}</h1><p>{description}</p></div><Button variant="outline" onClick={onBack}><LayoutDashboard size={15} /> Resumen</Button></div>{children}</>; }
function Metric({ icon: Icon, label, value, note, tone = "ink" }: { icon: typeof Activity; label: string; value: string; note: string; tone?: string }) { return <div className="metric"><div className={`metric-icon ${tone}`}><Icon size={16} /></div><div><span>{label}</span><strong>{value}</strong><small>{note}</small></div></div>; }
function PanelHeading({ eyebrow, title, action, onClick }: { eyebrow: string; title: string; action?: string; onClick?: () => void }) { return <div className="panel-heading"><div><div className="panel-eyebrow">{eyebrow}</div><h2>{title}</h2></div>{onClick && <button onClick={onClick}>{action}<ArrowUpRight size={14} /></button>}</div>; }
function EventTimeline({ events }: { events: EventItem[] }) { return <div className="timeline">{events.map((item) => <div className="timeline-item" key={item.id}><div className="timeline-rail"><span className="timeline-dot" /></div><div className="timeline-body"><div className="timeline-top"><strong>{item.event.replaceAll("_", " ")}</strong><span>{formatTime(item.timestamp)}</span></div><p>{item.source} · {item.session_date}{item.direction ? ` · ${item.direction}` : ""}</p>{item.r_multiple != null && <Badge className={item.r_multiple >= 0 ? "badge-positive" : "badge-negative"}>{item.r_multiple >= 0 ? "+" : ""}{item.r_multiple.toFixed(2)}R</Badge>}</div></div>)}</div>; }
function InfoCard({ icon: Icon, title, value, detail }: { icon: typeof Activity; title: string; value: string; detail: string }) { return <div className="panel info-card"><Icon size={19} /><div><span>{title}</span><strong>{value}</strong><p>{detail}</p></div></div>; }
function FlowStep({ n, title, text }: { n: string; title: string; text: string }) { return <div className="flow-step"><span>{n}</span><div><strong>{title}</strong><p>{text}</p></div></div>; }
function ConfigRow({ label, value }: { label: string; value: string }) { return <div className="config-row"><span>{label}</span><strong>{value}</strong></div>; }
function Dependency({ label, value, icon: Icon }: { label: string; value: string; icon: typeof Activity }) { const good = value.toLowerCase().includes("healthy"); return <div className="dependency"><Icon size={16} /><span>{label}</span><strong className={good ? "positive" : "warning-text"}>{value}</strong></div>; }
